### PR TITLE
Support Choosing Camera

### PR DESCRIPTION
**Pull request by Brahmah**
This pull adds support for specifying the camera that should be streamed from.

See updated docs for further information.

I am aware this pull is quite brief but have nothing more to add.

Resolves Issues:
#18 (partially)
#23

### CODE REVIEW

**Comment by jeroenterheerdt** [comment]
thanks!

**Comment by angadsingh** [comment]
@Brahmah any significant improvements on bumping the ring-client-api from 9.6.0 to 9.12.4?

**Comment by Brahmah** [comment]
@angadsingh Yes! Resolved an issue where some devices would not live stream due to a ring API change.

**Comment by nutsofamily** [comment]
How do I add this new pull to the hassio repository?

**Comment by 400HPMustang** [comment]
Is this going to get merged to master? or how can I just add this to my current installation?

**Pull request merged**
